post_install() {
echo "*************************************************************
Add line 'export QT_QPA_PLATFORMTHEME=qt5gtk2' to ~/.profile and re-login.
Alternatively, create the file /etc/X11/Xsession.d/100-qt5gtk2 with
the following line:

export QT_QPA_PLATFORMTHEME=qt5gtk2

Now restart X11 server to take the changes effect.

Attention!
Environment variable QT_STYLE_OVERRIDE should be removed before usage.
*************************************************************";
}
